### ISSUE TITLE
strange behaviour on exception in map

### ISSUE THREAD

**Issue by stoeffel** [futurize/future-io#19]
See https://github.com/futurize/future-io/blob/strange-test-behavior/test/node-fs.js#L9
Tests run forever...

**Comment by jwoudenberg** [comment]
I believe this is something to do with ava. When I try breaking the `examples/even` script in the same way and run that, I get a nice TypeError.

**Comment by jwoudenberg** [comment]
Yeah, seems async errors are an issue that's actively worked on: https://github.com/sindresorhus/ava/search?q=uncaught&type=Issues&utf8=%E2%9C%93

**Comment by stoeffel** [comment]
oki. so close for now
