### ISSUE TITLE
First release

### ISSUE THREAD

**Issue by jwoudenberg** [futurize/future-io#2]
Stuff that needs to happen before we can go public with this. Feel free to add additional points.

- [x] #3 Add features missing for MVL.
- [x] #4 Decide on node versions to support (>=4.x).
- [x] Dump Ramda (it's hardly used at the moment).
- [x] #5 Finalise README.
- [ ] Setup CI.
- [ ] tag and `npm publish`.

**Comment by stoeffel** [comment]
done. I moved it over and OS-ed it.

**Comment by jwoudenberg** [comment]
Thanks! Publishes v1.0.0, added some badges and enabled greenkeeper.
